// Generated by `libxr gen`; do not edit by hand.
// Generated from mspm0g3507_minidb48.syscfg (MSPM0G3507); SysConfig configures the
// clocks, pins, DMA channels and peripherals (SYSCFG_DL_init() in main.c). Put
// application code between the "User Code Begin" and "User Code End" markers.
#include "app_main.h"

#include "libxr.hpp"
#include "mspm0_gpio.hpp"
#include "mspm0_i2c.hpp"
#include "mspm0_power.hpp"
#include "mspm0_pwm.hpp"
#include "mspm0_spi.hpp"
#include "mspm0_timebase.hpp"
#include "mspm0_uart.hpp"
#include "ti_msp_dl_config.h"
#include "xrobot_main.hpp"

using namespace LibXR;

/* User Code Begin 1 */
#include <atomic>
// KEY interrupt counters, incremented in the GPIO interrupt callbacks.
static std::atomic<uint32_t> key1_irq_count{0};
static std::atomic<uint32_t> key2_irq_count{0};

static void OnKeyInterrupt(bool in_isr, std::atomic<uint32_t>* count)
{
  (void)in_isr;
  count->fetch_add(1, std::memory_order_relaxed);
}

// Terminal command `key`: prints the KEY1/KEY2 interrupt counters.
static int KeyCommand(int, char**)
{
  LibXR::STDIO::Print<"KEY1 {} KEY2 {}\r\n">(key1_irq_count.load(), key2_irq_count.load());
  return 0;
}
/* User Code End 1 */

// Input clocks: the BUSCLK of the power domain. PD0 from ULPCLK = CPUCLK_FREQ / 2
// (DL_SYSCTL_setULPCLKDivider) and PD1 from MCLK (CPUCLK_FREQ). The I2C driver resets
// the clock configuration of its peripherals, so the BUSCLK of the domain is the right
// argument.
static constexpr uint32_t PD0_BUSCLK_FREQ = (CPUCLK_FREQ / 2);
static constexpr uint32_t PD1_BUSCLK_FREQ = CPUCLK_FREQ;

// Ownership of the DMA channels that serve a UART transmitter;
// MSPM0_UART_MAIN_INIT checks these names against the ones SysConfig generated.
#define DMA_CH_UART0_TX_LIBXR_UART_IRQN UART_0_INST_INT_IRQN
#define DMA_CH_UART0_TX_LIBXR_UART_TX 1
#define DMA_CH_UART1_TX_LIBXR_UART_IRQN UART_1_INST_INT_IRQN
#define DMA_CH_UART1_TX_LIBXR_UART_TX 1

// DMA buffers. A UART gets 2 x N bytes for its two transmit halves; the receive side
// runs on byte interrupts. The SPI DMA buffers are split in two halves as well; the
// I2C driver uses polling, its buffer is the staging area for DMA transfers.
alignas(size_t) static uint8_t uart0_tx_buf[2 * 128];
alignas(size_t) static uint8_t uart1_tx_buf[2 * 64];
alignas(4) static uint8_t spi1_rx_buf[64];
alignas(4) static uint8_t spi1_tx_buf[64];
alignas(4) static uint8_t i2c0_buf[32];
alignas(4) static uint8_t i2c1_buf[32];

extern "C" void app_main(void)
{
  /* User Code Begin 2 */
  /* User Code End 2 */

  // Timebase and platform
  static MSPM0Timebase timebase;
  PlatformInit();
  static MSPM0PowerManager power_manager;

  // GPIO: SysConfig configured LED1 (PB8), LED2 (PA16) as output pins and KEY1 (PB24),
  // KEY2 (PB20) as input pins. The interrupt edge comes from SysConfig; RegisterCallback
  // and EnableInterrupt belong to the consumer (a Module or the User Code).
  static MSPM0GPIO LED1(GPIO_LEDS_PIN_LED1_PORT, GPIO_LEDS_PIN_LED1_PIN,
                        GPIO_LEDS_PIN_LED1_IOMUX);
  static MSPM0GPIO LED2(GPIO_LEDS_PIN_LED2_PORT, GPIO_LEDS_PIN_LED2_PIN,
                        GPIO_LEDS_PIN_LED2_IOMUX);
  static MSPM0GPIO KEY1(GPIO_KEYS_PORT, GPIO_KEYS_PIN_KEY1_PIN, GPIO_KEYS_PIN_KEY1_IOMUX);
  static MSPM0GPIO KEY2(GPIO_KEYS_PORT, GPIO_KEYS_PIN_KEY2_PIN, GPIO_KEYS_PIN_KEY2_IOMUX);

  // UART: TX with DMA; the receive side runs on byte interrupts.
  static MSPM0UART uart0(MSPM0_UART_MAIN_INIT(UART_0, DMA_CH_UART0_TX, uart0_tx_buf,
                         sizeof(uart0_tx_buf), 5, 128));
  static MSPM0UART uart1(MSPM0_UART_MAIN_INIT(UART_1, DMA_CH_UART1_TX, uart1_tx_buf,
                         sizeof(uart1_tx_buf), 5, 64));

  // I2C: polling; the buffer stages DMA transfers.
  static MSPM0I2C i2c0(MSPM0_I2C_INIT(I2C_0, PD0_BUSCLK_FREQ, i2c0_buf, sizeof(i2c0_buf),
                       8), {I2C_0_BUS_SPEED_HZ});
  static MSPM0I2C i2c1(MSPM0_I2C_INIT(I2C_1, PD0_BUSCLK_FREQ, i2c1_buf, sizeof(i2c1_buf),
                       8), {I2C_1_BUS_SPEED_HZ});

  // SPI: DMA for transfers longer than the threshold.
  static MSPM0SPI spi1(MSPM0_SPI_INIT(SPI_1, PD1_BUSCLK_FREQ, DMA_CH_SPI1_RX,
                       DMA_CH_SPI1_TX, spi1_rx_buf, sizeof(spi1_rx_buf), spi1_tx_buf,
                       sizeof(spi1_tx_buf), 3));

  // PWM: the channels of one timer share one period, which SysConfig configures.
  static MSPM0PWM pwm_tima1_c0(MSPM0_PWM_CH(PWM_TIMA1, 0));
  pwm_tima1_c0.SetConfig({1000});
  static MSPM0PWM pwm_tima1_c1(MSPM0_PWM_CH(PWM_TIMA1, 1));

  // Terminal on uart0
  STDIO::read_ = uart0.read_port_;
  STDIO::write_ = uart0.write_port_;
  static RamFS ramfs("XRobot");
  static Terminal<32, 32, 5, 5> terminal(ramfs);
  static auto terminal_task = Timer::CreateTask(terminal.TaskFun, &terminal, 10);
  Timer::Add(terminal_task);
  Timer::Start(terminal_task);

  // Hardware registration
  XR_REGISTER(power_manager, LibXR::PowerManager);

  XR_REGISTER(LED1, LibXR::GPIO);
  XR_REGISTER(LED2, LibXR::GPIO);
  XR_REGISTER(KEY1, LibXR::GPIO);
  XR_REGISTER(KEY2, LibXR::GPIO);

  XR_REGISTER(pwm_tima1_c0, LibXR::PWM);
  XR_REGISTER(pwm_tima1_c1, LibXR::PWM);

  XR_REGISTER(spi1, LibXR::SPI);

  XR_REGISTER(uart0, LibXR::UART);
  XR_REGISTER(uart1, LibXR::UART);

  XR_REGISTER(i2c0, LibXR::I2C);
  XR_REGISTER(i2c1, LibXR::I2C);

  XR_REGISTER(ramfs, LibXR::RamFS);

  XR_REGISTER(terminal, LibXR::Terminal<32, 32, 5, 5>);

  /* User Code Begin 3 */
  // The keys pull the pin low against an external 15k pull-up: falling edge, no internal
  // pull.
  KEY1.SetConfig({GPIO::Direction::FALL_INTERRUPT, GPIO::Pull::NONE});
  KEY1.RegisterCallback(GPIO::Callback::Create(OnKeyInterrupt, &key1_irq_count));
  KEY1.EnableInterrupt();
  KEY2.SetConfig({GPIO::Direction::FALL_INTERRUPT, GPIO::Pull::NONE});
  KEY2.RegisterCallback(GPIO::Callback::Create(OnKeyInterrupt, &key2_irq_count));
  KEY2.EnableInterrupt();

  // Add the `key` and `power` commands to the RamFS root, where the terminal looks them
  // up; `power bootloader` resets into the ROM BSL for serial flashing.
  static auto key_command = RamFS::CreateCommand("key", KeyCommand);
  ramfs.Add(key_command);
  power_manager.RegisterCommand(ramfs);
  /* User Code End 3 */
  XROBOT_MAIN();
}
